name: Testing Secret Variables

on:
  workflow_dispatch

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Secret Variable"
        run: |
          echo "This is a secret: ${{ secrets.MY_KEY }}"
          ${{ secrets.MY_KEY }}
